/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "AlphaBuilder",
  "tagline": "Quant Research Project",
  "favicon": "img/favicon_1.png",
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": true,
      "useCssCascadeLayers": true
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "url": "https://alphabuilder.xyz",
  "baseUrl": "/",
  "organizationName": "Jeetmu",
  "projectName": "AlphaBuilder-Site",
  "trailingSlash": false,
  "onBrokenLinks": "warn",
  "onBrokenMarkdownLinks": "warn",
  "deploymentBranch": "gh-pages",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": false,
        "blog": false,
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "themes": [
    [
      "/Users/homebrew/Documents/AB-S/AlphaBuilder-System/alphabuilder_site/node_modules/@easyops-cn/docusaurus-search-local/dist/server/server/index.js",
      {
        "hashed": true,
        "indexDocs": false,
        "indexBlog": false,
        "indexPages": true,
        "searchBarPosition": "right",
        "searchBarShortcut": false,
        "searchResultLimits": 4
      }
    ]
  ],
  "themeConfig": {
    "navbar": {
      "style": "dark",
      "logo": {
        "alt": "AlphaBuilder Logo",
        "src": "/img/Logo_4.svg"
      },
      "items": [
        {
          "type": "dropdown",
          "to": "/signals",
          "label": "Signals",
          "position": "left",
          "className": "center-navbar",
          "items": [
            {
              "to": "/signals/price_return_features",
              "label": "Price / Return Features"
            },
            {
              "to": "/signals/moving_averages",
              "label": "Moving Averages"
            },
            {
              "to": "/signals/technical_indicators",
              "label": "Technical Indicators"
            },
            {
              "to": "/signals/fundamental_indicators",
              "label": "Fundamental Indicators"
            },
            {
              "to": "/signals/formulaic_alphas",
              "label": "Formulaic Alphas"
            },
            {
              "to": "/signals/regime_aware_signals",
              "label": "Regime-Aware Signals"
            },
            {
              "to": "/signals/volatility_garch_signals",
              "label": "Volatility / GARCH Signals"
            },
            {
              "to": "/signals/statistical_arb_signals",
              "label": "Statistical / Arb Signals"
            },
            {
              "to": "/signals/network_aware_signals",
              "label": "Network-Aware Signals"
            },
            {
              "to": "/signals/entropy_based_signals",
              "label": "Entropy-Based Signals"
            },
            {
              "to": "/signals/fractal_based_signals",
              "label": "Fractal-Based Signals"
            },
            {
              "to": "/signals/event_sentiment_signals",
              "label": "Event / Sentiment Signals "
            },
            {
              "to": "/signals/multi_resolution_signals",
              "label": "Multi-Resolution Signals"
            },
            {
              "to": "/signals/regime_weighted_features",
              "label": "Regime-Weighted Features"
            },
            {
              "to": "/signals/derived_meta_signals",
              "label": "Derived / Meta Signals"
            }
          ]
        },
        {
          "type": "dropdown",
          "to": "/risk",
          "label": "Risk",
          "position": "left",
          "className": "center-navbar",
          "items": [
            {
              "to": "/risk/basic_statistical_risk",
              "label": "Basic Statistical Risk"
            },
            {
              "to": "/risk/distribution_based_risk",
              "label": "Distribution-Based Risk"
            },
            {
              "to": "/risk/volatility_modelling",
              "label": "Volatility Modeling"
            },
            {
              "to": "/risk/multi_asset_cross_asset_volatility",
              "label": "Multi-Asset / Cross-Asset Volatility"
            },
            {
              "to": "/risk/regime_aware_risk",
              "label": "Regime-Aware Risk"
            },
            {
              "to": "/risk/scenario_stress_testing",
              "label": "Scenario & Stress Testing"
            },
            {
              "to": "/risk/correlation_network_risk",
              "label": "Correlation & Network Risk"
            },
            {
              "to": "/risk/signal_to_risk_mapping",
              "label": "Signal-to-Risk Mapping"
            },
            {
              "to": "/risk/bayesian_probabilistic_risk",
              "label": "Bayesian / Probabilistic Risk"
            },
            {
              "to": "/risk/entropy_based_risk",
              "label": "Entropy-Based Risk"
            },
            {
              "to": "/risk/rl_dynamic_risk_control",
              "label": "RL-Based Dynamic Risk Control"
            },
            {
              "to": "/risk/factor_exposure_constraints",
              "label": "Factor / Exposure Constraints"
            },
            {
              "to": "/risk/tail_extreme_event_risk",
              "label": "Tail / Extreme Event Risk"
            },
            {
              "to": "/risk/rolling_multi_horizon_risk",
              "label": "Rolling / Multi-Horizon Risk"
            },
            {
              "to": "/risk/derived_hybrid_risk_signals",
              "label": "Derived / Hybrid Risk Signals"
            }
          ]
        },
        {
          "type": "dropdown",
          "to": "/optimizer",
          "label": "Optimizer",
          "position": "left",
          "className": "center-navbar",
          "items": [
            {
              "to": "/optimizer/classical_portfolio_optimization",
              "label": "Classical Portfolio Optimization"
            },
            {
              "to": "/optimizer/risk_adjusted_optimization",
              "label": "Risk-Adjusted Optimization"
            },
            {
              "to": "/optimizer/factor_exposure_constraints",
              "label": "Factor / Exposure Constraints"
            },
            {
              "to": "/optimizer/heuristic_optimization",
              "label": "Heuristic Optimization"
            },
            {
              "to": "/optimizer/non_convex_optimization",
              "label": "Non-Convex Optimization"
            },
            {
              "to": "/optimizer/multi_objective_pareto_optimization",
              "label": "Multi-Objective / Pareto Optimization"
            },
            {
              "to": "/optimizer/regime_aware_optimization",
              "label": "Regime-Aware Optimization"
            },
            {
              "to": "/optimizer/rl_based_portfolio_optimization",
              "label": "RL-Based Portfolio Optimization"
            },
            {
              "to": "/optimizer/scenario_stress_aware_optimization",
              "label": "Scenario / Stress-Aware Optimization"
            },
            {
              "to": "/optimizer/meta_learning_cross_asset_adaptation",
              "label": "Meta-Learning / Cross-Asset Adaptation"
            },
            {
              "to": "/optimizer/multi_horizon_optimization",
              "label": "Multi-Horizon Optimization"
            },
            {
              "to": "/optimizer/hybrid_ensemble_optimization",
              "label": "Hybrid / Ensemble Optimization"
            },
            {
              "to": "/optimizer/entropy_based_allocation",
              "label": "Entropy-Based Allocation"
            },
            {
              "to": "/optimizer/diversification_based_allocation",
              "label": "Diversification-Based Allocation"
            },
            {
              "to": "/optimizer/derived_composite_objectives",
              "label": "Derived / Composite Objectives"
            },
            {
              "to": "/optimizer/network_aware_optimization",
              "label": "Network Aware Optimization"
            }
          ]
        },
        {
          "type": "dropdown",
          "to": "/vega",
          "label": "Vega",
          "position": "left",
          "className": "center-navbar",
          "items": [
            {
              "to": "/vega/volatility_foundations",
              "label": "Volatility Foundations"
            },
            {
              "to": "/vega/stochastic_volatility_models",
              "label": "Stochastic Volatility Models"
            },
            {
              "to": "/vega/regime_switching_volatility_models",
              "label": "Regime-Switching Volatility Models"
            },
            {
              "to": "/vega/volatility_surface_construction",
              "label": "Volatility Surface Construction"
            },
            {
              "to": "/vega/volatility_smile_skew_analysis",
              "label": "Volatility Smile & Skew Analysis"
            },
            {
              "to": "/vega/gaussian_process_implied_volatility",
              "label": "Gaussian Process Implied Volatility"
            },
            {
              "to": "/vega/deep_volatility_models",
              "label": "Deep Volatility Models"
            },
            {
              "to": "/vega/regime_aware_pricing",
              "label": "Regime-Aware Pricing"
            },
            {
              "to": "/vega/calibration_engine",
              "label": "Calibration Engine"
            },
            {
              "to": "/vega/volatility_risk_premium",
              "label": "Volatility Risk Premium"
            },
            {
              "to": "/vega/vega_risk_sensitivity_analysis",
              "label": "Vega-Risk & Sensitivity Analysis"
            },
            {
              "to": "/vega/volatility_forecasting_layer",
              "label": "Volatility Forecasting Layer"
            },
            {
              "to": "/vega/hybrid_meta_volatility_models",
              "label": "Hybrid / Meta Volatility Models"
            }
          ]
        },
        {
          "type": "dropdown",
          "to": "/hub",
          "label": "Hub",
          "position": "left",
          "className": "center-navbar",
          "items": [
            {
              "to": "/hub/feature_engineering",
              "label": "Feature Engineering"
            },
            {
              "to": "/hub/tree_based_module",
              "label": "Tree Based Module"
            },
            {
              "to": "/hub/integrated_module",
              "label": "Integrated Module"
            },
            {
              "to": "/hub/cascade_modeling",
              "label": "Cascade Modeling"
            },
            {
              "to": "/hub/encoder_layer",
              "label": "Encoder Layer"
            },
            {
              "to": "/hub/transformer_attention_layer",
              "label": "Transformer / Attention Layer"
            },
            {
              "to": "/hub/gan_generative",
              "label": "GAN / Generative Layer"
            },
            {
              "to": "/hub/skating_fusion_layer",
              "label": "Skating Fusion Layer"
            },
            {
              "to": "/hub/gating_layer",
              "label": "Gating Layer"
            },
            {
              "to": "/hub/meta_learning",
              "label": "Meta-Learning"
            },
            {
              "to": "/hub/auto_regime_discovery",
              "label": "Auto Regime Discovery"
            },
            {
              "to": "/hub/explainability_attribution",
              "label": "Explainability / Attribution"
            },
            {
              "to": "/hub/rl_based_layer",
              "label": "RL-Based Layer"
            },
            {
              "to": "/hub/forecast_head_decoder",
              "label": "Forecast Head / Decoder"
            }
          ]
        },
        {
          "type": "dropdown",
          "to": "/system",
          "label": "System",
          "position": "left",
          "className": "center-navbar",
          "items": [
            {
              "to": "/system/dashboard",
              "label": "Dashboard"
            },
            {
              "to": "/system/alpaca_trade",
              "label": "Alpaca Trade"
            },
            {
              "to": "/system/numerai",
              "label": "Numerai"
            },
            {
              "to": "/system/numerai_signals",
              "label": "Numerai Signals"
            }
          ]
        },
        {
          "type": "dropdown",
          "to": "/community/contact",
          "label": "Community",
          "position": "left",
          "className": "center-navbar",
          "items": [
            {
              "to": "/community/research",
              "label": "Research"
            },
            {
              "to": "/community/blog",
              "label": "Blogs"
            },
            {
              "to": "/community/status",
              "label": "Status"
            },
            {
              "to": "/community/about",
              "label": "About"
            },
            {
              "to": "/community/contact",
              "label": "Contact"
            },
            {
              "href": "https://discord.gg/rz6wPGYQBH",
              "label": "Discord",
              "target": "_blank"
            }
          ]
        }
      ],
      "hideOnScroll": false
    },
    "colorMode": {
      "defaultMode": "dark",
      "disableSwitch": true,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "prism": {
      "additionalLanguages": [],
      "theme": {
        "plain": {
          "color": "#bfc7d5",
          "backgroundColor": "#292d3e"
        },
        "styles": [
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(105, 112, 152)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "inserted"
            ],
            "style": {
              "color": "rgb(195, 232, 141)"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "rgb(247, 140, 108)"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function"
            ],
            "style": {
              "color": "rgb(130, 170, 255)"
            }
          },
          {
            "types": [
              "punctuation",
              "selector"
            ],
            "style": {
              "color": "rgb(199, 146, 234)"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "rgb(191, 199, 213)"
            }
          },
          {
            "types": [
              "class-name",
              "attr-name"
            ],
            "style": {
              "color": "rgb(255, 203, 107)"
            }
          },
          {
            "types": [
              "tag",
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 114)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "rgb(137, 221, 255)"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "rgb(255, 88, 116)"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "doctype"
            ],
            "style": {
              "color": "rgb(199, 146, 234)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "rgb(178, 204, 214)"
            }
          },
          {
            "types": [
              "url"
            ],
            "style": {
              "color": "rgb(221, 221, 221)"
            }
          }
        ]
      },
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  }
};
